package view;

import javax.swing.*;

public class DeleteWindow extends JFrame {

	private static final long serialVersionUID = 3160815239687590889L;
	private JButton jButtonCancel;
	private JButton jButtonErase;
	private JLabel jLabel3;
	private JTextField jTextFieldID;

	/**
	 * Creates new form Window_Delete
	 */
	public DeleteWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jLabel3 = new JLabel();
		jTextFieldID = new JTextField();
		jButtonErase = new JButton();
		jButtonCancel = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("Borrar Registro");
		setResizable(false);

		jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel3.setText("OF:");

		jTextFieldID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

		jButtonErase.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jButtonErase.setText("Borrar OF");


		jButtonCancel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jButtonCancel.setText("Cancelar");


		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jButtonErase)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonCancel)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel3)
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextFieldID)))
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonErase)
								.addComponent(jButtonCancel))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}

	public JButton getjButtonErase() {
		return this.jButtonErase;
	}

	public JButton getjButtonCancel() {
		return this.jButtonCancel;
	}

	public JLabel getjLabel3() {
		return jLabel3;
	}

	public JTextField getjTextFieldID() {
		return jTextFieldID;
	}


}
